language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - mkdir cmake
  - cd cmake
  - wget https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.sh
  - sh cmake-3.4.1-Linux-x86_64.sh --exclude-subdir --skip-license
  - cd ..

  - sudo apt-get install -y libgtest-dev
  - mkdir gtest_build
  - cd gtest_build
  - ../cmake/bin/cmake /usr/src/gtest
  - make
  - sudo cp *.a /usr/lib
  - cd ..

script:
  - mkdir build
  - cd build
  - ../cmake/bin/cmake -DBUILD_DEMO=0 -DBUILD_TEST=1 ..
  - make
  - ./kletch_test
