language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libgtest-dev
  - mkdir gtest_build
  - cd gtest_build
  - cmake /usr/src/gtest
  - make
  - sudo cp *.a /usr/lib
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_PREFIX_PATH:PATH=/usr -DGTEST_ROOT:PATH=/usr -DBUILD_DEMO=0 -DBUILD_TEST=1 ..
  - make
  - ./kletch_test
