language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_DEMO=0 -DBUILD_TEST=1 ..
  - make
  - ./kletch_test

notifications:
  email: false
