language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - echo Hello

script:
  - ls /usr/share/cmake/Modules/

  - mkdir build
  - cd build
  - cmake -DBUILD_DEMO=0 -DBUILD_TEST=1 ..
  - ls gtest/src/gtest_external
  - make VERBOSE=1
  - ./kletch_test
