language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - echo Hello

script:
  - mkdir build
  - cd build
  - cmake -DBUILD_DEMO=0 -DBUILD_TEST=1 ..
  - make
  - ./kletch_test
